version: '3'

vars:
  # Get the list of all local crates, excluding the target directory.
  # You can also set it manually: CRATES: crate_a crate_b
  CRATES:
    sh: cargo metadata --no-deps --format-version 1 | jq -r '.packages[].name'

tasks:
  default:
    cmds:
      - task: list

  list:
    desc: List all tasks in the current project
    cmds:
      - task --list
  
  lint:
    desc: Run linters on all crates
    silent: true
    cmds:
      - cargo clippy --workspace -- -D warnings

  build:
    desc: Build all crates
    cmds:
      - cargo build --workspace

  test:
    desc: Run tests, excluding the Tauri desktop on Linux
    silent: true
    cmds:
      - task: lint
      - cargo test --workspace

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean
