// ⚠️ Side-effect import must come first: protects the JSON-RPC channel
// by redirecting console output to stderr.
import "./console-guard.js";
// ── Protocol types (generated by ts-rs) ────────────────────────────
export * from "./types/index.js";
// ── ora global API object ──────────────────────────────────────────
// Plugin developers use: import { ora } from "@ora-space/plugin-sdk"
// The object is populated by bootstrap() before activate() is called.
export { getOra as ora } from "./sdk.js";
// ── SDK entry point ────────────────────────────────────────────────
// Used by the built-in entry script (ora-plugin-entry.ts).
// Plugin developers do NOT call this directly.
export { bootstrap } from "./sdk.js";
