// This file was generated by `cargo xtask export-contracts`. Do not edit this file manually.
import type { CreateProjectRequest, CreateProjectResponse, DeleteProjectRequest, DeleteProjectResponse, GetProjectRequest, GetProjectResponse, ListProjectsRequest, ListProjectsResponse, UpdateProjectRequest, UpdateProjectResponse } from "./project.js";
import type { OpenProjectWorkContextRequest, OpenProjectWorkContextResponse, RenewProjectWorkContextRequest, RenewProjectWorkContextResponse } from "./project-work-context.js";
import type { CreateSessionRequest, CreateSessionResponse, DeleteSessionRequest, DeleteSessionResponse, GetSessionRequest, GetSessionResponse, ListSessionsRequest, ListSessionsResponse, UpdateSessionRequest, UpdateSessionResponse } from "./session.js";
import type { CreateTaskRequest, CreateTaskResponse, DeleteTaskRequest, DeleteTaskResponse, GetTaskRequest, GetTaskResponse, ListTasksRequest, ListTasksResponse, UpdateTaskRequest, UpdateTaskResponse } from "./task.js";
import type { CreateWorktreeRequest, CreateWorktreeResponse, DeleteWorktreeRequest, DeleteWorktreeResponse, GetWorktreeRequest, GetWorktreeResponse, ListWorktreesRequest, ListWorktreesResponse, UpdateWorktreeRequest, UpdateWorktreeResponse } from "./worktree.js";
import type { HttpMethod } from "./transport.js";

export type EndpointPathParam = {
  rustFieldName: string;
  wireName: string;
};

export type FrontendEndpointDefinition = {
  operationName: string;
  method: HttpMethod;
  pathTemplate: string;
  requestType: string;
  responseType: string;
  pathParams: readonly EndpointPathParam[];
  hasJsonBody: boolean;
};

export type RequestByOperation = {
  createProject: CreateProjectRequest;
  getProject: GetProjectRequest;
  listProjects: ListProjectsRequest;
  updateProject: UpdateProjectRequest;
  deleteProject: DeleteProjectRequest;
  openProjectWorkContext: OpenProjectWorkContextRequest;
  renewProjectWorkContext: RenewProjectWorkContextRequest;
  createTask: CreateTaskRequest;
  getTask: GetTaskRequest;
  listTasks: ListTasksRequest;
  updateTask: UpdateTaskRequest;
  deleteTask: DeleteTaskRequest;
  createWorktree: CreateWorktreeRequest;
  getWorktree: GetWorktreeRequest;
  listWorktrees: ListWorktreesRequest;
  updateWorktree: UpdateWorktreeRequest;
  deleteWorktree: DeleteWorktreeRequest;
  createSession: CreateSessionRequest;
  getSession: GetSessionRequest;
  listSessions: ListSessionsRequest;
  updateSession: UpdateSessionRequest;
  deleteSession: DeleteSessionRequest;
};

export type ResponseByOperation = {
  createProject: CreateProjectResponse;
  getProject: GetProjectResponse;
  listProjects: ListProjectsResponse;
  updateProject: UpdateProjectResponse;
  deleteProject: DeleteProjectResponse;
  openProjectWorkContext: OpenProjectWorkContextResponse;
  renewProjectWorkContext: RenewProjectWorkContextResponse;
  createTask: CreateTaskResponse;
  getTask: GetTaskResponse;
  listTasks: ListTasksResponse;
  updateTask: UpdateTaskResponse;
  deleteTask: DeleteTaskResponse;
  createWorktree: CreateWorktreeResponse;
  getWorktree: GetWorktreeResponse;
  listWorktrees: ListWorktreesResponse;
  updateWorktree: UpdateWorktreeResponse;
  deleteWorktree: DeleteWorktreeResponse;
  createSession: CreateSessionResponse;
  getSession: GetSessionResponse;
  listSessions: ListSessionsResponse;
  updateSession: UpdateSessionResponse;
  deleteSession: DeleteSessionResponse;
};

export type EndpointOperation = keyof RequestByOperation;

export const endpoints = {
  createProject: {
    operationName: "createProject",
    method: "POST",
    pathTemplate: "/api/projects",
    requestType: "CreateProjectRequest",
    responseType: "CreateProjectResponse",
    pathParams: [],
    hasJsonBody: true,
  },
  getProject: {
    operationName: "getProject",
    method: "GET",
    pathTemplate: "/api/projects/{projectId}",
    requestType: "GetProjectRequest",
    responseType: "GetProjectResponse",
    pathParams: [{ rustFieldName: "project_id", wireName: "projectId" }],
    hasJsonBody: false,
  },
  listProjects: {
    operationName: "listProjects",
    method: "GET",
    pathTemplate: "/api/projects",
    requestType: "ListProjectsRequest",
    responseType: "ListProjectsResponse",
    pathParams: [],
    hasJsonBody: false,
  },
  updateProject: {
    operationName: "updateProject",
    method: "PUT",
    pathTemplate: "/api/projects/{projectId}",
    requestType: "UpdateProjectRequest",
    responseType: "UpdateProjectResponse",
    pathParams: [{ rustFieldName: "project_id", wireName: "projectId" }],
    hasJsonBody: true,
  },
  deleteProject: {
    operationName: "deleteProject",
    method: "DELETE",
    pathTemplate: "/api/projects/{projectId}",
    requestType: "DeleteProjectRequest",
    responseType: "DeleteProjectResponse",
    pathParams: [{ rustFieldName: "project_id", wireName: "projectId" }],
    hasJsonBody: false,
  },
  openProjectWorkContext: {
    operationName: "openProjectWorkContext",
    method: "POST",
    pathTemplate: "/api/project-work-contexts/open",
    requestType: "OpenProjectWorkContextRequest",
    responseType: "OpenProjectWorkContextResponse",
    pathParams: [],
    hasJsonBody: true,
  },
  renewProjectWorkContext: {
    operationName: "renewProjectWorkContext",
    method: "POST",
    pathTemplate: "/api/project-work-contexts/renew",
    requestType: "RenewProjectWorkContextRequest",
    responseType: "RenewProjectWorkContextResponse",
    pathParams: [],
    hasJsonBody: true,
  },
  createTask: {
    operationName: "createTask",
    method: "POST",
    pathTemplate: "/api/tasks",
    requestType: "CreateTaskRequest",
    responseType: "CreateTaskResponse",
    pathParams: [],
    hasJsonBody: true,
  },
  getTask: {
    operationName: "getTask",
    method: "GET",
    pathTemplate: "/api/tasks/{taskId}",
    requestType: "GetTaskRequest",
    responseType: "GetTaskResponse",
    pathParams: [{ rustFieldName: "task_id", wireName: "taskId" }],
    hasJsonBody: false,
  },
  listTasks: {
    operationName: "listTasks",
    method: "GET",
    pathTemplate: "/api/tasks",
    requestType: "ListTasksRequest",
    responseType: "ListTasksResponse",
    pathParams: [],
    hasJsonBody: false,
  },
  updateTask: {
    operationName: "updateTask",
    method: "PUT",
    pathTemplate: "/api/tasks/{taskId}",
    requestType: "UpdateTaskRequest",
    responseType: "UpdateTaskResponse",
    pathParams: [{ rustFieldName: "task_id", wireName: "taskId" }],
    hasJsonBody: true,
  },
  deleteTask: {
    operationName: "deleteTask",
    method: "DELETE",
    pathTemplate: "/api/tasks/{taskId}",
    requestType: "DeleteTaskRequest",
    responseType: "DeleteTaskResponse",
    pathParams: [{ rustFieldName: "task_id", wireName: "taskId" }],
    hasJsonBody: false,
  },
  createWorktree: {
    operationName: "createWorktree",
    method: "POST",
    pathTemplate: "/api/worktrees",
    requestType: "CreateWorktreeRequest",
    responseType: "CreateWorktreeResponse",
    pathParams: [],
    hasJsonBody: true,
  },
  getWorktree: {
    operationName: "getWorktree",
    method: "GET",
    pathTemplate: "/api/worktrees/{worktreeId}",
    requestType: "GetWorktreeRequest",
    responseType: "GetWorktreeResponse",
    pathParams: [{ rustFieldName: "worktree_id", wireName: "worktreeId" }],
    hasJsonBody: false,
  },
  listWorktrees: {
    operationName: "listWorktrees",
    method: "GET",
    pathTemplate: "/api/worktrees",
    requestType: "ListWorktreesRequest",
    responseType: "ListWorktreesResponse",
    pathParams: [],
    hasJsonBody: false,
  },
  updateWorktree: {
    operationName: "updateWorktree",
    method: "PUT",
    pathTemplate: "/api/worktrees/{worktreeId}",
    requestType: "UpdateWorktreeRequest",
    responseType: "UpdateWorktreeResponse",
    pathParams: [{ rustFieldName: "worktree_id", wireName: "worktreeId" }],
    hasJsonBody: true,
  },
  deleteWorktree: {
    operationName: "deleteWorktree",
    method: "DELETE",
    pathTemplate: "/api/worktrees/{worktreeId}",
    requestType: "DeleteWorktreeRequest",
    responseType: "DeleteWorktreeResponse",
    pathParams: [{ rustFieldName: "worktree_id", wireName: "worktreeId" }],
    hasJsonBody: false,
  },
  createSession: {
    operationName: "createSession",
    method: "POST",
    pathTemplate: "/api/sessions",
    requestType: "CreateSessionRequest",
    responseType: "CreateSessionResponse",
    pathParams: [],
    hasJsonBody: true,
  },
  getSession: {
    operationName: "getSession",
    method: "GET",
    pathTemplate: "/api/sessions/{sessionId}",
    requestType: "GetSessionRequest",
    responseType: "GetSessionResponse",
    pathParams: [{ rustFieldName: "session_id", wireName: "sessionId" }],
    hasJsonBody: false,
  },
  listSessions: {
    operationName: "listSessions",
    method: "GET",
    pathTemplate: "/api/sessions",
    requestType: "ListSessionsRequest",
    responseType: "ListSessionsResponse",
    pathParams: [],
    hasJsonBody: false,
  },
  updateSession: {
    operationName: "updateSession",
    method: "PUT",
    pathTemplate: "/api/sessions/{sessionId}",
    requestType: "UpdateSessionRequest",
    responseType: "UpdateSessionResponse",
    pathParams: [{ rustFieldName: "session_id", wireName: "sessionId" }],
    hasJsonBody: true,
  },
  deleteSession: {
    operationName: "deleteSession",
    method: "DELETE",
    pathTemplate: "/api/sessions/{sessionId}",
    requestType: "DeleteSessionRequest",
    responseType: "DeleteSessionResponse",
    pathParams: [{ rustFieldName: "session_id", wireName: "sessionId" }],
    hasJsonBody: false,
  },
} satisfies Record<EndpointOperation, FrontendEndpointDefinition>;
