// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed events pushed from the backend toward the frontend.
 *
 * Each variant carries its own payload and serializes as a tagged JSON object
 * (`{ "type": "...", ... }`) so the frontend can discriminate on `event.type`.
 */
export type Northbound = {
  "type": "session_title_updated";
  session_id: string;
  title: string;
};
